### PR TITLE
RATEST-257:Remove selenium legacy Tests and Pages

### PR DESCRIPTION
**Pull request by sherrif10**
https://issues.openmrs.org/browse/RATEST-257

### CODE REVIEW

**Review by sherrif10 — COMMENTED** [review]
cc @kdaud  Looking forward for your reviews.

**Comment by kdaud** [comment]
@sheriff10 are the selenium legacy tests migrated into qaframework master?

**Comment by sherrif10** [comment]
Hello @kdaud . Can we get this approaved since everything is in qaframework module

**Comment by kdaud** [comment]
@sherrif10 I think its a good idea to have this merged when all the tests are migrated into qa module.

**Review by kdaud — APPROVED** [review]
cc: @dkayiwa

**Pull request merged**
