### PR TITLE
SYNCT-205: "Setup UI tests environment for FHIR mapping"

### PR DESCRIPTION
**Pull request by tomaszmueller**

### CODE REVIEW

**Comment by tomaszmueller** [comment]
do not merge

**Comment by dkayiwa** [comment]
@tomaszmueller do you plan to throw this away? 😊

**Comment by tomaszmueller** [comment]
@dkayiwa I need to add some more changes to this PR before merging but have higher priority tasks right now. You can close it if you have to as it may take some time before I'll be able to update it

**Comment by dkayiwa** [comment]
OK. Feel free to reopen when you resume working on it. 😊

**Pull request closed without merging**
